// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Tweet struct {
	ID        string `json:"id"`
	AuthorID  string `json:"authorId"`
	Text      string `json:"text"`
	TweetedAt string `json:"tweetedAt"`
}

type TwitterUser struct {
	ID       string  `json:"id"`
	Username *string `json:"username"`
	Name     *string `json:"name"`
}
