name: Frontend Web CI

on:
  push:
    paths:
      - frontend/web/**
      - .github/workflows/frontend-web-ci.yml

defaults:
  run:
    working-directory: frontend/web

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: frontend/web/yarn.lock

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build