name: Infrastructure CI for dev environment

on:
  push:
    paths:
      - infrastructure/dev/**
      - .github/workflows/infrastructure-dev-ci.yml

defaults:
  run:
    working-directory: infrastructure/dev

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_DEV }}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform format
        run: terraform fmt -recursive -check

      - name: Terraform validate
        run: terraform validate

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan