name: Infrastructure CD for dev environment

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - infrastructure/module/**
      - infrastructure/dev/**
      - .github/workflows/infrastructure-dev-cd.yml

defaults:
  run:
    working-directory: infrastructure/dev

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_DEV }}

jobs:
  cd:
    name: CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform format
        run: terraform fmt -recursive -check

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        run: terraform apply