name: Tweet collector batch CD

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
    paths:
      - backend/batch/tweet-collector/**
      - .github/workflows/tweet-collector-cd.yml

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    outputs:
      dev-url: ${{ steps.deploy-dev.outputs.url }}
      prd-url: ${{ steps.deploy-prd.outputs.url }}
    steps:
      - uses: actions/checkout@v3

      - name: Auth dev environment
        if: ${{ github.ref_name == 'develop' }}
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_DEV }}

      - name: Auth prd environment
        if: ${{ github.ref_name == 'main' }}
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_PRD }}
      
      - id: deploy-dev
        name: Deploy dev environment
        if: ${{ github.ref_name == 'develop' }}
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: tweet-collector
          region: asia-northeast1
          source: backend/batch/tweet-collector
          env_vars: 'TWITTER_API_BEARER_TOKEN=${{ secrets.TWITTER_API_BEARER_TOKEN_DEV }}'

      - id: deploy-prd
        name: Deploy prd environment
        if: ${{ github.ref_name == 'main' }}
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: tweet-collector
          region: asia-northeast1
          source: backend/batch/tweet-collector
          env_vars: 'TWITTER_API_BEARER_TOKEN=${{ secrets.TWITTER_API_BEARER_TOKEN_PRD }}'

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Test dev environment connection
        if: ${{ github.ref_name == 'develop' }}
        run: curl ${{ needs.deploy.outputs.dev-url }}

      - name: Test prd environment connection
        if: ${{ github.ref_name == 'main' }}
        run: curl ${{ needs.deploy.outputs.prd-url }}